services:
  site:
    build:
      context: .
      dockerfile: dockerfile.site
    container_name: hackemon-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hackemon

  jeu:
    build:
      context: .
      dockerfile: dockerfile.jeu
    container_name: hackemon-jeu
    restart: unless-stopped
    ports:
      - "3001:8080"
    depends_on:
      - site

  mongo:
    image: mongo:6.0
    container_name: hackemon-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
